CREATE TABLE [dbo].[PromoPreConfigDetail]
(
[PromoPreConfigDetailID] [int] NOT NULL IDENTITY(1, 1),
[PromoPreConfigID] [int] NOT NULL,
[PromoName] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PromoDescription] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Startdate] [datetime] NULL,
[Enddate] [datetime] NULL,
[ProcessStartDate] [datetime] NULL,
[ProcessEndDate] [datetime] NULL,
[ActivityStartDate] [datetime] NULL,
[ActivityEndDate] [datetime] NULL,
[OptInBeginDate] [datetime] NULL,
[OptInEndDate] [datetime] NULL,
[WagerDays] [tinyint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_WagerDays] DEFAULT ((0)),
[RebateAmount] [decimal] (11, 2) NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_RebateAmount] DEFAULT ((0.00)),
[MatchAmount] [decimal] (11, 2) NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_MatchAmount] DEFAULT ((0.00)),
[CallCenterVisible] [bit] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_CallCenterVisible] DEFAULT ((1)),
[PromoTypeId] [smallint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_PromoTypeID] DEFAULT ((18)),
[StepLimit] [smallint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_StepLimit] DEFAULT ((0)),
[RewardPoints] [int] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_RewardPoints] DEFAULT ((0)),
[RebatePCT] [decimal] (5, 2) NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_RebatePCT] DEFAULT ((0)),
[RebateLimit] [decimal] (11, 2) NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_RebateLimit] DEFAULT ((0)),
[PromotionPaymentLimitID] [tinyint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_PromoPaymentLimitID] DEFAULT ((2)),
[ChannelOutLetId] [smallint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_ChannelOutLetID] DEFAULT ((418)),
[ChannelPromoCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_ChannelPromoCode] DEFAULT (''),
[ValidStateList] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_ValidStateList] DEFAULT ('ALL'),
[WebSiteEnabled] [bit] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_WebSiteEnabled] DEFAULT ((0)),
[DefaultPromoCode] [bit] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_DefaultPromoCode] DEFAULT ((0)),
[PrePromoText] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_PrePromoText] DEFAULT (''),
[PostPromoText] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_PostPromoTest] DEFAULT (''),
[OLGDefault] [bit] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_OLGDefault] DEFAULT ((0)),
[ChannelName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_ChannelName] DEFAULT ('TV Guide Interactive Programming Guide'),
[ChannelTypeID] [tinyint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_ChannelTypeID] DEFAULT ((1)),
[HoursVisible] [bit] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_HoursVisible] DEFAULT ((0)),
[PoolTypeList] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_PoolTypeList] DEFAULT ('ALL'),
[TrackList] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_TrackList] DEFAULT ('ALL'),
[RaceList] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_RaceList] DEFAULT ('0'),
[Percentage] [decimal] (4, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_Percentage] DEFAULT ((0)),
[ExpandPoolFlag] [tinyint] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_ExpandPoolFlag] DEFAULT ((0)),
[betStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_BetStatus] DEFAULT (''),
[PlatformList] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SiteID] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BettingInterest] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_BettingInterest] DEFAULT ('0'),
[MaxPromoAmount] [decimal] (11, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_MaxPromoAmount] DEFAULT ((0)),
[MaxBatchAmount] [decimal] (11, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_MaxBatchAmount] DEFAULT ((0)),
[MaxDailyAmount] [decimal] (11, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_MaxDailyAmount] DEFAULT ((0)),
[OddsModifier] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[raceDate] [date] NULL,
[OptInActivityOverrideTypeID] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_OptInActivityOverrideTypeID] DEFAULT ((0)),
[WagerDaysActivityOverrideTypeID] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_WagerDaysActivityOverrideTypeID] DEFAULT ((0)),
[PromotionEntryTypeID] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_PromoEntryTypeID] DEFAULT ((0)),
[BatchPayoutTypeID] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_BatchPayoutTypeID] DEFAULT ((4)),
[CashPrizeAmount] [decimal] (11, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_CashPrizeAmount] DEFAULT ((0)),
[ParentPromoID] [int] NULL,
[OrdinalPosition] [smallint] NULL CONSTRAINT [DF_PromoPreConfigDetail_OrdinalPosition] DEFAULT ('0'),
[ParentOrdinalPosition] [smallint] NULL CONSTRAINT [DF_PromoPreConfigDetail_ParentOrdinalPosition] DEFAULT ('0'),
[PayoutSegmentMovePermissionTypeID] [smallint] NULL CONSTRAINT [DF_PromoPreConfigDetail_PayoutSegmentMovePermissionTypeID] DEFAULT ('0'),
[SegmentID] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_SegmentID] DEFAULT ('0'),
[DepositPaymentType] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepositBonusAmount] [decimal] (15, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_DepositBonusAmount] DEFAULT ('0'),
[DepositBonusPercent] [decimal] (5, 2) NULL CONSTRAINT [DF_PromoPreConfigDetail_DepositBonusPercent] DEFAULT ('0'),
[ActivityLimit] [int] NULL CONSTRAINT [DF_PromoPreConfigDetail_ActivityLimit] DEFAULT ((100000)),
[PromoID] [int] NULL,
[MarketingCategoryID] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_MarketingCategoryID] DEFAULT ((1)),
[RewardsBoost] [smallint] NULL CONSTRAINT [DF_PromoPreConfigDetail_RewardsBoost] DEFAULT ((0)),
[FinishingPosition] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_FinishingPosition] DEFAULT ((0)),
[MinBettingInterests] [tinyint] NULL CONSTRAINT [DF_PromoPreConfigDetail_MinBettingInterests] DEFAULT ((0)),
[AdditionalTags] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PromoPreConfigDetail_AdditionalTags] DEFAULT (''),
[IsActive] [bit] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_IsActive] DEFAULT ((1)),
[LastUpdatedDate] [datetime] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_LastUpdatedDate] DEFAULT (getdate()),
[LastUpdatedBy] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_LastUpdatedBy] DEFAULT ('SysAdmin'),
[CreatedDate] [datetime] NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_CreatedDate] DEFAULT (getdate()),
[CreatedBy] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_CreatedBy] DEFAULT ('SysAdmin'),
[JiraLink] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PromoFriendlyName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PromoPreConfigDetail_PromoFriendlyName] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PromoPreConfigDetail] ADD CONSTRAINT [PK_PromoPreConfigDetail_PromoPreConfigID] PRIMARY KEY CLUSTERED  ([PromoPreConfigDetailID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PromoPreConfigDetail] ADD CONSTRAINT [FK_PromoPreConfigDetail_PromoPreConfig] FOREIGN KEY ([PromoPreConfigID]) REFERENCES [dbo].[PromoPreConfig] ([PromoPreConfigID])
GO
